name: Deploy to Okunolab Super Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        
      - name: build
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 9.7.1
          run: |
            pnpm install
            pnpm build

      - name: Setup SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_github_action
          config: |
            Host ${{ secrets.SSH_HOST }}
              HostName ${{ secrets.SSH_HOST }}
              User ${{ secrets.SSH_USER }}
              Port ${{ secrets.SSH_PORT }}
              IdentityFile ~/.ssh/id_github_action
          known_hosts: |
            ${{ secrets.SSH_KNOWN_HOSTS }}
      
      - name: Deploy to server
        run: |
          echo "Deploying to server..."
          echo "Creating logs directory... ${{ secrets.DEPLOY_PATH }}/logs"
          ssh ${{ secrets.SSH_HOST }} "mkdir -p ${{ secrets.DEPLOY_PATH }}/logs"

          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo 'Deploy started at $(date)' >> ${{ secrets.DEPLOY_PATH }}/logs/deploy.log"
          
          scp -r ./dist/* ${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_PATH }}

          ssh ${{ secrets.SSH_HOST }} "echo 'Deploy finished at $(date)' >> ${{ secrets.DEPLOY_PATH }}/logs/deploy.log"
